export const _genre = {
    1: "Fantasia",
    2: "Ficção científica",
    3: "Distopia",
    4: "Ação",
    5: "Aventura",
    6: "Romance",
    7: "Mistério",
    8: "Suspense",
    9: "Thriller",
    10: "Horror",
    11: "Ficção Policial",
    12: "Ficção histórica",
    13: "Ficção Contemporânea",
    14: "Realismo mágico",
    15: "Drama",
    16: "Comédia",
    17: "Sátira",
    18: "Ficção Feminina",
    19: "Infantil",
    20: "Conto",
    21: "Super-heróis",
    22: "Vampiros",
    23: "Lobisomens",
    24: "Zumbis",
    25: "Fantasma",
    26: "Alienígenas",
    27: "Viagem no tempo",
    28: "Desastre",
    29: "Sobrevivência",
    30: "Espionagem",
    31: "Crime",
    32: "Guerra",
    33: "História Alternativa",
    34: "História Verídica",
    35: "Mitologia",
    36: "Folclore",
    37: "Sagas",
    38: "Arte e Fotografia",
    39: "Gastronomia",
    40: "Memórias e autobiografia",
    41: "Biografia",
    42: "Autoajuda",
    43: "Relatos de Viagem",
    44: "Diários e Correspondências",
    45: "Ensaios",
    46: "Guias e Manuais",
    47: "Arte",
    48: "Ciência",
    49: "História",
    50: "Natureza",
    51: "Animais",
    52: "Tecnologia",
    53: "Religião",
    54: "Filosofia",
    55: "Política",
    56: "Economia",
    57: "Psicologia",
    58: "Sociologia",
    59: "Antropologia",
    60: "Arqueologia",
    61: "Astronomia",
    62: "Geografia",
    63: "Matemática",
    64: "Física",
    65: "Química",
    66: "Biologia",
    67: "Medicina",
    68: "Direito",
    69: "Educação",
    70: "Agricultura",
    71: "Culinária",
    72: "Moda",
    73: "Design",
    74: "Arquitetura",
    75: "Engenharia",
    76: "Negócios",
    77: "Finanças",
    78: "Marketing",
    79: "Vendas",
    80: "Gerenciamento",
    81: "Liderança",
    82: "Empreendedorismo",
    83: "Investimento",
    84: "Imóveis",
    85: "Carreira",
    86: "Produtividade",
    87: "Auto-aperfeiçoamento",
    88: "Motivação",
    89: "Inspiração",
    90: "Sucesso",
    91: "Amor",
    92: "Relacionamento",
    93: "Casamento",
    94: "Paternidade",
    95: "Maternidade",
    96: "Infância",
    97: "Adolescência",
    98: "Adulto",
    99: "Envelhecimento",
    100: "Morte",
    101: "Luto",
    102: "Saúde",
    103: "Fitness",
    104: "Nutrição",
    105: "Dieta",
    106: "Yoga",
    107: "Meditação",
    108: "Espiritualidade"
}


export const _type = {
    0: 'Comum',
    1: 'Mangá',
    2: 'Novel',
    3: 'Enciclopédia',
    4: 'Didático',
    5: 'Colorir',
    6: 'Receita',
    7: 'Autoajuda',
    8: 'Viagem',
    9: 'Manual',
}

export const _lang = {
    0: 'Português',
    1: 'Inglês',
    2: 'Espanhol',
    3: 'Francês',
    4: 'Alemão',
    5: 'Italiano',
    6: 'Russo',
    7: 'Japonês',
    8: 'Chinês',
    9: 'Árabe',
    10: 'Coreano',
    11: 'Grego',
    12: 'Latim',
    13: 'Polonês'
}

export const _book_condition = {
    0: 'Lacrado',
    1: 'Novo',
    2: 'Usado',
    3: 'Desgastado',
    4: 'Bem Desgastado',
}

export const _feedbacks = {
    1: 'Atencioso',
    2: 'Educado',
    3: 'Simpático',
    4: 'Rápido',
    5: 'Paciente',
    6: 'Detalhista',
}